"use client"

import Header from "@/components/header"
import './globals.css'
import { Providers } from "@/utils/redux/provider"
import VristoSidebar from "@/components/sideBarTest"


export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className="bg-white">
    <head>
      <title>FrontEnd App For Beelder</title>
    </head>
    <body>
      <Header />
      <VristoSidebar />
      <div className="bg-white">
        <Providers>{children}</Providers>
      </div>
    </body>
  </html>
  )
}

