import Header from "@/components/header"
import './globals.css'
import { Provider } from "react-redux";
import { store } from "../utils/store";

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className="bg-white">
    <head>
      <title>FrontEnd App For Beelder</title>
    </head>
    <body>
      <Header />
      <Provider store={store}>{children}</Provider>
    </body>
  </html>
  )
}

